# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidTraker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'

  # Pods for CovidTraker

  target 'CovidTrakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovidTrakerUITests' do
    # Pods for testing
  end

end
